version: '3.8'

services:
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    networks:
      - fielddock
    environment:
      DJANGO_SETTINGS_MODULE: "fielddock.settings.docker"
    depends_on:
      mysqldb:
        condition: service_healthy
      mqtt:
        condition: service_healthy
    command: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  mysqldb:
    restart: unless-stopped
    image: mysql:8.3
    ports:
      - 3306:3306
    volumes:
      - fielddock-mysql:/var/lib/mysql
    networks:
      - fielddock
    environment:
      MYSQL_ROOT_PASSWORD: "passw0rd"
      MYSQL_DATABASE: dev
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10
  mqtt:
    restart: unless-stopped
    image: eclipse-mosquitto:2.0
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - fielddock
    healthcheck:
      test: [ "CMD", "mosquitto_pub", "-h", "localhost", "-t", "test", "-m", "test" ]
      timeout: 5s
      retries: 10

volumes:
  fielddock-mysql:

networks:
  fielddock: {}