# Generated by Django 4.2.7 on 2024-02-08 19:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('battery', models.CharField(blank=True, max_length=50, null=True)),
                ('gps_location', models.CharField(blank=True, max_length=50, null=True)),
                ('telemetry_data', models.TextField(blank=True, null=True)),
                ('camera', models.CharField(blank=True, max_length=50, null=True)),
                ('field_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drones', to='admin_site.fieldcomponent')),
            ],
        ),
        migrations.CreateModel(
            name='EdgeComputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('storage_capacity', models.FloatField(blank=True, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=50, null=True)),
                ('field_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_computers', to='admin_site.fieldcomponent')),
            ],
        ),
        migrations.CreateModel(
            name='Hanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('door_status', models.BooleanField(default=False)),
                ('field_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hangers', to='admin_site.fieldcomponent')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(max_length=100)),
                ('model_number', models.CharField(max_length=100)),
                ('specifications', models.TextField(blank=True, null=True)),
                ('edge_computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='devices.edgecomputer')),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('value', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='devices.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='HangerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('hanger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='devices.hanger')),
            ],
        ),
        migrations.CreateModel(
            name='EdgeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('edge_computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='devices.edgecomputer')),
            ],
        ),
        migrations.CreateModel(
            name='DroneLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='devices.drone')),
            ],
        ),
    ]
