# Generated by Django 4.2.7 on 2024-02-23 21:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('field_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='admin_site.fieldcomponent')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_date', models.DateTimeField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('mission_status', models.CharField(choices=[('Planned', 'Planned'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('waypoints', models.TextField()),
                ('waypoints_raw', models.TextField()),
                ('weather_conditions', models.CharField(blank=True, max_length=255, null=True)),
                ('field_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='admin_site.fieldcomponent')),
            ],
        ),
        migrations.CreateModel(
            name='PlotIndices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var', models.CharField(max_length=100)),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('area_all', models.FloatField()),
                ('area_veg', models.FloatField()),
                ('geometry', models.TextField()),
                ('mean_blue', models.FloatField()),
                ('mean_green', models.FloatField()),
                ('mean_red', models.FloatField()),
                ('mean_rededge', models.FloatField()),
                ('mean_nir', models.FloatField()),
                ('ndvi_y', models.FloatField()),
                ('gndvi', models.FloatField()),
                ('rvi_1', models.FloatField()),
                ('gci', models.FloatField()),
                ('rgvi', models.FloatField()),
                ('dvi', models.FloatField()),
                ('savi', models.FloatField()),
                ('msavi', models.FloatField()),
                ('osavi', models.FloatField()),
                ('rdvi', models.FloatField()),
                ('tvi', models.FloatField()),
                ('tsavi', models.FloatField()),
                ('pvi', models.FloatField()),
                ('savi_2', models.FloatField()),
                ('atsavi', models.FloatField()),
                ('ndwi', models.FloatField()),
                ('npci', models.FloatField()),
                ('srpi', models.FloatField()),
                ('rvi_2', models.FloatField()),
                ('mcari', models.FloatField()),
                ('mcari_1', models.FloatField()),
                ('mcari_2', models.FloatField()),
                ('mtvi_1', models.FloatField()),
                ('mtvi_2', models.FloatField()),
                ('r_mcari_mtvi_2', models.FloatField()),
                ('evi', models.FloatField()),
                ('datt', models.FloatField()),
                ('ndci', models.FloatField()),
                ('psri', models.FloatField()),
                ('sipi', models.FloatField()),
                ('spvi', models.FloatField()),
                ('tcari', models.FloatField()),
                ('r_tcari_osavi', models.FloatField()),
                ('reri', models.FloatField()),
                ('ndre', models.FloatField()),
                ('mtci', models.FloatField()),
                ('evi_2', models.FloatField()),
                ('reci', models.FloatField()),
                ('nexg', models.FloatField()),
                ('ngrdi', models.FloatField()),
                ('endvi', models.FloatField()),
                ('ari_2', models.FloatField()),
                ('cri_2', models.FloatField()),
                ('nrvi', models.FloatField()),
                ('osavi_2', models.FloatField()),
                ('evi_3', models.FloatField()),
                ('mevi', models.FloatField()),
                ('vari', models.FloatField()),
                ('tvi_2', models.FloatField()),
                ('mcari_osavi', models.FloatField()),
                ('tcari_osavi', models.FloatField()),
                ('wdrvi', models.FloatField()),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plot_indices', to='missions.mission')),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_number', models.CharField(max_length=50)),
                ('size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_info', models.TextField(blank=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='missions.crop')),
            ],
        ),
        migrations.CreateModel(
            name='ImageOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('image_type', models.CharField(choices=[('Downsample', 'Downsample'), ('Heatmap', 'Heatmap'), ('Orthomosaic', 'Orthomosaic')], max_length=20)),
                ('image', models.FileField(upload_to='imageout_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageout', to='missions.mission')),
            ],
        ),
        migrations.CreateModel(
            name='EdgeStateMachineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edge_state_machine_statuses', to='missions.mission')),
            ],
        ),
        migrations.CreateModel(
            name='DroneStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('battery_percentage', models.FloatField()),
                ('speed', models.FloatField()),
                ('mission_duration', models.DurationField()),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drone_statuses', to='missions.mission')),
            ],
        ),
        migrations.CreateModel(
            name='CloudStateMachineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_state_machine_statuses', to='missions.mission')),
            ],
        ),
    ]
